const blogActionTypes = {
  ADD_CONTENT: "ADD_CONTENT",
  DELETE_CONTENT: "DELETE_CONTENT",
  GET_CONTENT: "GET_CONTENT",
  FETCH_BLOG: "FETCH_BLOG",
  UPDATE_CONTENT: "UPDATE_CONTENT",
  TOGGLE_SORTBY: "TOGGLE_SORTBY",
};

export default blogActionTypes;
